### ISSUE TITLE
ValueError: The following `model_kwargs` are not used by the model: ['cache', 'agents']

### ISSUE THREAD

**Issue by thinhlpg** [siddharthverma314/chai-naacl-2022#2]
Hello, I'm facing this problem when trying to run `generate_sentences`:
```
ValueError: The following `model_kwargs` are not used by the model: ['cache', 'agents'] (note: typos in the generate arguments will also show up in this list)
```

I tried to look up in this project and HuggingFace documentation, but found no clue.
Can you please let me know the exact version of the `transformers` library you used in this project? Or if you have any solution to fix this issue, please let me know. Thank you!

```
python generate_sentences.py logs/gpt2/checkpoint-20
```

Full traceback:

```
(py38chai) thinhlpg@G14 ~/code/chai-naacl-2022/scripts/transformers (main)$ python generate_sentences.py logs/gpt2/checkpoin
t-20
Opening input file...
Loading GPT...
  0%|                                                                                             | 0/47986 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "generate_sentences.py", line 26, in <module>
    val = gpt.generate(
  File "/home/thinhlpg/code/chai-naacl-2022/neural_chat/gpt2/gpt2.py", line 101, in generate
    generated = generation_fn(
  File "/home/thinhlpg/code/chai-naacl-2022/neural_chat/gpt2/gpt2.py", line 77, in generate_best
    return self.model.generate(
  File "/home/thinhlpg/anaconda3/envs/py38chai/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 26, in decorate_context
    return func(*args, **kwargs)
  File "/home/thinhlpg/anaconda3/envs/py38chai/lib/python3.8/site-packages/transformers/generation/utils.py", line 1267, in generate
    self._validate_model_kwargs(model_kwargs.copy())
  File "/home/thinhlpg/anaconda3/envs/py38chai/lib/python3.8/site-packages/transformers/generation/utils.py", line 1140, in _validate_model_kwargs
    raise ValueError(
ValueError: The following `model_kwargs` are not used by the model: ['cache', 'agents'] (note: typos in the generate arguments will also show up in this list)
```

**Comment by QpxDesign** [comment]
I also encountered this issue. I downgraded transformers to 4.21.0, as suggested by a reply to an [issue in the transformers repo](https://github.com/huggingface/transformers/issues/19290), and I was able to run generate_sentences  successfully.
