### ISSUE TITLE
Fail when run scripts training RL Agent

### ISSUE THREAD

**Issue by hungnq1310** [siddharthverma314/chai-naacl-2022#3]
I have problem when running scripts 
``` 
python chai_emaq.py \
	   --logdir ./logs/chai \
	   --filepath ./data/train.json \
	   --embeddings <PATH TO embeddings.pkl> \
	   --sentences <PATH TO sentences.pkl>
```
I follow normally the sequential tutorial in file README, however I encounter this error:  
```
Sun May 28 05:40:50 2023| Wrote file
  0%|                                                  | 0/5000 [00:00<?, ?it/s]
  0%|                                                    | 0/43 [00:01<?, ?it/s]
  0%|                                                  | 0/5000 [00:01<?, ?it/s]
Traceback (most recent call last):
  File "/kaggle/working/hero1310/scripts/train/chai_emaq.py", line 80, in <module>
    algo.update(sample, j)
  File "/kaggle/working/hero1310/neural_chat/algo/sac.py", line 126, in update
    self.update_critic(**batch)
  File "/kaggle/working/hero1310/neural_chat/algo/emaq_no_actor.py", line 133, in update_critic
    next_act = self.actor.action(next_obs)
  File "/kaggle/working/hero1310/neural_chat/actor/base.py", line 21, in action
    return self.action_with_log_prob(obs, deterministic)[0]
  File "/kaggle/working/hero1310/neural_chat/actor/craigslist_dummy_actor.py", line 68, in action_with_log_prob
    indices, log_prob_utterance = self.q_handler.sample_with_log_prob(
  File "/kaggle/working/hero1310/neural_chat/actor/craigslist_emaq_actor.py", line 34, in sample_with_log_prob
    dist = self._get_dist(obs, act, num_actions)
  File "/kaggle/working/hero1310/neural_chat/actor/craigslist_emaq_actor.py", line 23, in _get_dist
    qs = self.q_fn(obs, act)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/kaggle/working/hero1310/neural_chat/critic/doubleq.py", line 37, in forward
    return torch.min(*self.double_q(obs, action))
  File "/kaggle/working/hero1310/neural_chat/critic/doubleq.py", line 31, in double_q
    q1, q2 = self.qf_1(obs_action), self.qf_2(obs_action)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/kaggle/working/hero1310/neural_chat/utils/mlp.py", line 33, in forward
    return self.mlp.forward(x)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/container.py", line 217, in forward
    input = module(input)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: mat1 and mat2 shapes cannot be multiplied (2560x1549 and 2061x256)
```
I think this error come from the shape of dataset itself or maybe some parameters of model/algo. Is I predict correctly or this repo has some special process elsewhere ?  Does it relate with the changing keyword I has processed below ?

Additional information: 
-----------
When running scripts for generating sentences, I has changed some keyword to avoid this below error:
```
ValueError: The following `model_kwargs` are not used by the model: ['cache', 'agents'] (note: typos in the generate arguments will also show up in this list)
```
For more specific, I changed `cache` to `use_cache` and remove keyword `agents`. I can understand keyword `cache` because of version of transformers, but why keyword `agents` is passed to generation function without processing, which leading to keyword `agents` is passed to `model_kwargs` and make the `validating keyword function` of Huggingface error.

**Comment by RafaelCostaF** [comment]
I'm having the same error.
![image](https://github.com/user-attachments/assets/a4c0aa86-52ae-4933-9bd8-0fc10ae9475b)

@hungnq1310 , how did you solve the problem?
